backend:

  name: git-gateway

  branch: main



media_folder:

  images/uploads



public_folder:

  /images/uploads






collections:


# ==========================
# PRODUCTS
# ==========================


  - name: "products"

    label: "Products"

    folder: "content/products/items"

    create: true

    slug: "{{slug}}"

    fields:


      - label: "Product Name"

        name: "name"

        widget: "string"



      - label: "Category"

        name: "category"

        widget: "select"

        options:

          - Toys & Games

          - Fashion & Dresses

          - Household Essentials

          - Electronics

          - Health & Beauty

          - Kitchenware

          - Special Offers



      - label: "Price"

        name: "price"

        widget: "number"



      - label: "Old Price"

        name: "oldPrice"

        widget: "number"

        required: false



      - label: "Discount"

        name: "discount"

        widget: "number"

        required: false



      - label: "Product Image"

        name: "image"

        widget: "image"



      - label: "Description"

        name: "description"

        widget: "text"



      - label: "Stock Available"

        name: "stock"

        widget: "boolean"

        default: true






# ==========================
# BANNERS
# ==========================


  - name: "banners"

    label: "Banners"

    folder: "content/banners/items"

    create: true

    slug: "{{slug}}"


    fields:


      - label: "Banner Title"

        name: "title"

        widget: "string"



      - label: "Description"

        name: "description"

        widget: "text"



      - label: "Banner Image"

        name: "image"

        widget: "image"



      - label: "Button Text"

        name: "buttonText"

        widget: "string"



      - label: "Link"

        name: "link"

        widget: "string"

        required: false
